### ISSUE TITLE
Support for FireFox

### ISSUE THREAD

**Issue by alipiry** [MohamadKh75/ShutHub#1]
Hi there, 

First of all, thank you for this amazing idea!

Please add FireFox extension if you can. 

Thanks

**Comment by alipiry** [comment]
If someone uses the [stylus](https://add0n.com/stylus.html), they can add this little code to their main style to avoid GitHub bullshit warning:
```css
 div[class*="flash flash-full js-notice flash-warn"] {
        display: none;
    }
```
